kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world
  - echo `pwd`


---
kind: pipeline
type: docker
name: foo2

steps:
- name: foo
  image: alpine
  commands:
  - echo this should never run if branch is develop
  - echo the current branch is $DRONE_BRANCH