version: '3'
services:
  db:
    image: mysql
    environment:
    #   MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gozero
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    restart: always
  etcd:
    image: quay.io/coreos/etcd:v3.3.25
    environment:
      ETCD_DATA_DIR: "/data"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_INITIAL_CLUSTER: "default=http://0.0.0.0:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
    volumes: 
      - ./etcd_data:/data
    restart: always
    ports: 
      - 127.0.0.1:2380:2380
      - 127.0.0.1:2379:2379
    ulimits:
      nofile:
        soft: 1024000
        hard: 1024000
    # entrypoint: sleep 30000
  redis:
    image: redis
    ports: 
      - 127.0.0.1:6379:6379

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080    